# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/extractor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/extractor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/extractor.proto\x12\textractor\"*\n\x16ProcessEXRBytesRequest\x12\x10\n\x08\x65xr_data\x18\x01 \x01(\x0c\"[\n\x17ProcessEXRBytesResponse\x12\x10\n\x08png_data\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x0f\n\x07message\x18\x04 \x01(\t\"M\n\x08\x45XRChunk\x12&\n\x06header\x18\x01 \x01(\x0b\x32\x14.extractor.EXRHeaderH\x00\x12\x0e\n\x04\x64\x61ta\x18\x02 \x01(\x0cH\x00\x42\t\n\x07\x63ontent\"E\n\tEXRHeader\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x12\n\ntotal_size\x18\x02 \x01(\x03\x12\x12\n\nchunk_size\x18\x03 \x01(\x05\"|\n\x08PNGChunk\x12&\n\x06header\x18\x01 \x01(\x0b\x32\x14.extractor.PNGHeaderH\x00\x12\x0e\n\x04\x64\x61ta\x18\x02 \x01(\x0cH\x00\x12-\n\x06status\x18\x03 \x01(\x0b\x32\x1b.extractor.ProcessingStatusH\x00\x42\t\n\x07\x63ontent\">\n\tPNGHeader\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x12\n\ntotal_size\x18\x03 \x01(\x03\"Z\n\x10ProcessingStatus\x12#\n\x04type\x18\x01 \x01(\x0e\x32\x15.extractor.StatusType\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08progress\x18\x03 \x01(\x02\"\x14\n\x12HealthCheckRequest\"M\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x14\n\x0cservice_name\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t*\x88\x01\n\nStatusType\x12\x12\n\x0eSTATUS_UNKNOWN\x10\x00\x12\x14\n\x10STATUS_RECEIVING\x10\x01\x12\x15\n\x11STATUS_PROCESSING\x10\x02\x12\x12\n\x0eSTATUS_SENDING\x10\x03\x12\x13\n\x0fSTATUS_COMPLETE\x10\x04\x12\x10\n\x0cSTATUS_ERROR\x10\x05\x32\xfd\x01\n\x11\x45xtractionService\x12X\n\x0fProcessEXRBytes\x12!.extractor.ProcessEXRBytesRequest\x1a\".extractor.ProcessEXRBytesResponse\x12@\n\x10ProcessEXRStream\x12\x13.extractor.EXRChunk\x1a\x13.extractor.PNGChunk(\x01\x30\x01\x12L\n\x0bHealthCheck\x12\x1d.extractor.HealthCheckRequest\x1a\x1e.extractor.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.extractor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUSTYPE']._serialized_start=707
  _globals['_STATUSTYPE']._serialized_end=843
  _globals['_PROCESSEXRBYTESREQUEST']._serialized_start=36
  _globals['_PROCESSEXRBYTESREQUEST']._serialized_end=78
  _globals['_PROCESSEXRBYTESRESPONSE']._serialized_start=80
  _globals['_PROCESSEXRBYTESRESPONSE']._serialized_end=171
  _globals['_EXRCHUNK']._serialized_start=173
  _globals['_EXRCHUNK']._serialized_end=250
  _globals['_EXRHEADER']._serialized_start=252
  _globals['_EXRHEADER']._serialized_end=321
  _globals['_PNGCHUNK']._serialized_start=323
  _globals['_PNGCHUNK']._serialized_end=447
  _globals['_PNGHEADER']._serialized_start=449
  _globals['_PNGHEADER']._serialized_end=511
  _globals['_PROCESSINGSTATUS']._serialized_start=513
  _globals['_PROCESSINGSTATUS']._serialized_end=603
  _globals['_HEALTHCHECKREQUEST']._serialized_start=605
  _globals['_HEALTHCHECKREQUEST']._serialized_end=625
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=627
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=704
  _globals['_EXTRACTIONSERVICE']._serialized_start=846
  _globals['_EXTRACTIONSERVICE']._serialized_end=1099
# @@protoc_insertion_point(module_scope)
