# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import extractor_pb2 as proto_dot_extractor__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/extractor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExtractionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessEXRBytes = channel.unary_unary(
                '/extractor.ExtractionService/ProcessEXRBytes',
                request_serializer=proto_dot_extractor__pb2.ProcessEXRBytesRequest.SerializeToString,
                response_deserializer=proto_dot_extractor__pb2.ProcessEXRBytesResponse.FromString,
                _registered_method=True)
        self.ProcessEXRStream = channel.stream_stream(
                '/extractor.ExtractionService/ProcessEXRStream',
                request_serializer=proto_dot_extractor__pb2.EXRChunk.SerializeToString,
                response_deserializer=proto_dot_extractor__pb2.PNGChunk.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/extractor.ExtractionService/HealthCheck',
                request_serializer=proto_dot_extractor__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=proto_dot_extractor__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class ExtractionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessEXRBytes(self, request, context):
        """Original unary RPC (kept for backward compatibility)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessEXRStream(self, request_iterator, context):
        """Bidirectional streaming RPC for large files
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExtractionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessEXRBytes': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessEXRBytes,
                    request_deserializer=proto_dot_extractor__pb2.ProcessEXRBytesRequest.FromString,
                    response_serializer=proto_dot_extractor__pb2.ProcessEXRBytesResponse.SerializeToString,
            ),
            'ProcessEXRStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ProcessEXRStream,
                    request_deserializer=proto_dot_extractor__pb2.EXRChunk.FromString,
                    response_serializer=proto_dot_extractor__pb2.PNGChunk.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=proto_dot_extractor__pb2.HealthCheckRequest.FromString,
                    response_serializer=proto_dot_extractor__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'extractor.ExtractionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('extractor.ExtractionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExtractionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessEXRBytes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/extractor.ExtractionService/ProcessEXRBytes',
            proto_dot_extractor__pb2.ProcessEXRBytesRequest.SerializeToString,
            proto_dot_extractor__pb2.ProcessEXRBytesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessEXRStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/extractor.ExtractionService/ProcessEXRStream',
            proto_dot_extractor__pb2.EXRChunk.SerializeToString,
            proto_dot_extractor__pb2.PNGChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/extractor.ExtractionService/HealthCheck',
            proto_dot_extractor__pb2.HealthCheckRequest.SerializeToString,
            proto_dot_extractor__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
